### ISSUE TITLE
Error 403 with make prep_lite

### ISSUE THREAD

**Issue by flaviens** [black-parrot/black-parrot-sim#11]
Hi there!

I'm trying to run the first steps but when running `make prep_lite -j10` on my Ubuntu 22.04 I get a HTTP 403 somewhere:

```
Cloning into '/home/user/gits/blackparrot/black-parrot-sim/sdk/yocto/meta-linux-mainline'...
fatal: unable to access 'https://git.sr.ht/~pbarker/meta-linux-mainline/': The requested URL returned error: 403
fatal: clone of 'https://git.sr.ht/~pbarker/meta-linux-mainline' into submodule path '/home/user/gits/blackparrot/black-parrot-sim/sdk/yocto/meta-linux-mainline' failed
Failed to clone 'meta-linux-mainline'. Retry scheduled
Cloning into '/home/user/gits/blackparrot/black-parrot-sim/sdk/yocto/meta-linux-mainline'...
fatal: unable to access 'https://git.sr.ht/~pbarker/meta-linux-mainline/': The requested URL returned error: 403
fatal: clone of 'https://git.sr.ht/~pbarker/meta-linux-mainline' into submodule path '/home/user/gits/blackparrot/black-parrot-sim/sdk/yocto/meta-linux-mainline' failed
Failed to clone 'meta-linux-mainline' a second time, aborting
fatal: Failed to recurse into submodule path 'sdk/yocto'
fatal: Failed to recurse into submodule path 'sdk'
make: *** [Makefile:12: checkout] Error 1
```

Is this a known error / do you know a workaround?

Thank you very much!
Flavien

**Comment by dpetrisko** [comment]
Hi Flavien, thanks for the issue. 

Yes, this is a known issue. There was an external repo we relied on that was moved, breaking the submodule. If you update the remote of the bp-yocto submodule to the one from this PR, it should resolve:

https://github.com/black-parrot-sdk/bp-yocto/pull/1

I'll make a PR when I get to a computer so no one else runs into this...

**Comment by flaviens** [comment]
Cool thanks! Then I'll retry when it's merged!

**Comment by dpetrisko** [comment]
Give this a shot: https://github.com/black-parrot/black-parrot-sim/pull/12

**Comment by flaviens** [comment]
That works! I'm getting the same segmentation fault as #10 but it seems benign from my understanding.

Thank you for your fast help!
Flavien
