### ISSUE TITLE
BlackParrot Floating Point Tests

### ISSUE THREAD

**Issue by amithmath** [black-parrot/black-parrot-sim#16]
Is there any floating points tests for black-parrot?

I think one need to add test(s) at bp-demos/src, add the test to the test_list in bp-demos/Makefile.frag, execute make bp-demos at the sdk root directory. I think this should build and install the test program to bp-demos with *.riscv. But I don't know how to use black-parrot floating point (FP) libraries (if any) for BP. 

It will be great some one could tell how a test program for FP addition look like?

**Comment by dpetrisko** [comment]
https://github.com/black-parrot-sdk/black-parrot-sdk

Many of these suites use FP

https://github.com/black-parrot-sdk/riscv-tests

FP assembly tests here

https://github.com/black-parrot-sdk/bp-tests/blob/master/src/fp_precision.c

Example of a c test with inline assembly 

Of course, just float x = 2.0 + 2.0 style operations work as well

**Comment by amithmath** [comment]
Thanks.
