### ISSUE TITLE
How to run BlackParrot with verilator？

### ISSUE THREAD

**Issue by zhangkanqi** [black-parrot/black-parrot-sim#18]
Hi!

I want to run   BlackParrot with verilator？ But I don't understand  how to do that after reading readme. Could u tell me the method?

Thanks :)

**Comment by dpetrisko** [comment]
Let us know what part of the docs is unclear so we can fix it for future users.

https://github.com/black-parrot/black-parrot/blob/master/docs/eval_guide.md
