### ISSUE TITLE
Verify Python package dependencies

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot-sim#3]
Surelog requires orderedmultidict, probably among other python packages. We should verify from a clean install which dependencies are required

**Comment by omasanori** [comment]
I will set up a clean and minimal CentOS 7 environment so that I can report on this in few days. I suspect that some packages (like `virtualenv`) are actually unused.

**Comment by omasanori** [comment]
Executing `sudo yum install python3-pip; pip install --user orderedmultidict` with a workaround https://github.com/black-parrot/black-parrot/pull/1057 was sufficient to build Surelog on CentOS 7.

**Comment by dpetrisko** [comment]
I believe all dependencies are accounted for with the latest changes; anyone, please feel free to correct me\
