### ISSUE TITLE
Path for BP_TOOLS_DIR in rtl Makefile.common incorrect

### ISSUE THREAD

**Issue by adithyasunil26** [black-parrot/black-parrot-sim#9]
Correct path for `BP_TOOLS_DIR` in `black-parrot-sim/rtl/Makefile.common` to `$(TOP)/../tools`

**Comment by dpetrisko** [comment]
Thanks! This should get resolved when we update this pointer to latest BP

**Comment by adithyasunil26** [comment]
Sounds good!

**Comment by dpetrisko** [comment]
Should be good now
